import = [
    "~/.config/alacritty/one.toml",
    "~/.config/alacritty/keybindings.toml"
]

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 10000

[window]
dynamic_title = true
opacity = 1
option_as_alt = "Both"

[window.dimensions]
columns = 170
lines = 50

[window.padding]
x = 2
y = 2
